### ISSUE TITLE
Multiple Indexes

### ISSUE THREAD

**Issue by borgcc** [mradamlacey/elasticsearch-tableau-connector#5]
Is it possible to have multiple indexes.  Similar to how elasticsearch api handles multiple indices separated by commas

**Comment by mradamlacey** [comment]
The only reason why this wouldn't work is if the Mapping API (that this connector calls to get the list of columns to return to Tableau) doesn't work or returns a slightly different response against an alias or list of indices like:

```
GET <cluster base url>:<port>/<index list or alias name>/<type name>/_mapping
```

I don't think adding support for this would be that difficult.  One thing to note is if multiple indices have different mappings for the same type, the connector would either return an error or pick one of the mappings and use that.  I would lean towards just picking the first mapping and somehow returning a message to the user.

**Comment by mradamlacey** [comment]
I just pushed a commit that adds support to:
- query indices and alias names using the Elasticsearch API
- query type names using the Elasticsearch API
- use typeahead controls to select the index/alias name, and then the type name instead of free-form text input

Some things to iron out:
- What type should be used if the same type name exists across multiple indices (in general this is not a best practice, or at least the types should be identical)
