### ISSUE TITLE
Do I need a tableau server ?

### ISSUE THREAD

**Issue by mnanirban** [mradamlacey/elasticsearch-tableau-connector#6]
Hi, Thanks for this connector , we were looking for similar implementation. I have few questions on how to install and run this. 
- Do I need a tableau server to install this? 
- Can this connector run as a webapp in a tomcat server ? 
- My office nw doesn't allow me to run grunt builds so how do I build it.

**Comment by mradamlacey** [comment]
- You don't need a Tableau server to use the connector.  You can run the connector locally and use Tableau Desktop to point at your local instance and pull in data.  In order to publish/share worksheets with other users - you will have to install to Tableau server
- No reason the connector can't run as a webapp in a tomcat server, it is purely static assets.  You will want to run:

```
grunt build:dist
```

And simply serve the contents of the `dist` folder from  Tomcat.
-  Not sure what restrictions your office has on grunt?  Do you mean you don't have internet access?  You will need to find a machine that does, run `npm install` and then copy the `node_modules` folder and copy that to your office environment.
