### ISSUE TITLE
Times being re-interpreted to UTC

### ISSUE THREAD

**Issue by chuchurocket27** [mradamlacey/elasticsearch-tableau-connector#61]
I have some date/time values in my ES data that look like this (UTC-7):

![image](https://cloud.githubusercontent.com/assets/21203338/26063670/81b2a836-3943-11e7-8b38-5047a7018884.png)

But when this value is brought into Tableau via the ES Connector, they are reinterpreted to UTC time:

![image](https://cloud.githubusercontent.com/assets/21203338/26063723/aea94ea8-3943-11e7-9fef-909bd1f60ade.png)

Is it possible to get the connector to read the field exactly as-is rather than change it to UTC?

**Comment by mradamlacey** [comment]
I think the fix needs to provide some UI to the user to let them override the default (interpret as UTC time) for each date field for the selected type.

**Comment by mradamlacey** [comment]
Can you check out the following branch: `utc-time-fix-date-fields`

There's a new option to 'Override Field Defaults' and 'Parse date fields in local time'

Check both of those and let me know if this gives the expected behavior. Unfortunately I dont think I have good test data to validate and I currently dont have a Tableau Desktop license.

It will also help if you can copy/paste the actual JSON for an example document and the mapping JSON for the type.  thanks!
